/* ═══════════════════════════════════════════════════════
   board-config.js — Board definitions for server-side compilation
   Defines MCU, toolchain, flags, and include paths per board.
   ═══════════════════════════════════════════════════════ */

'use strict';

const path = require('node:path');
const os = require('node:os');

const TOOLCHAIN_DIR = path.join(__dirname, 'toolchains');

function _toolchainPath(...parts) {
  const ext = os.platform() === 'win32' ? '.exe' : '';
  return path.join(TOOLCHAIN_DIR, ...parts) + ext;
}

const BOARDS = {
  arduino_uno: {
    name: 'Arduino Uno',
    toolchain: 'avr',
    mcu: 'atmega328p',
    fcpu: '16000000L',
    variant: 'standard',
    defines: [
      'ARDUINO=10819',
      'ARDUINO_AVR_UNO',
      'ARDUINO_ARCH_AVR',
      'F_CPU=16000000L',
    ],
    compiler: _toolchainPath('avr', 'bin', 'avr-gcc'),
    compilerCpp: _toolchainPath('avr', 'bin', 'avr-g++'),
    objcopy: _toolchainPath('avr', 'bin', 'avr-objcopy'),
    size: _toolchainPath('avr', 'bin', 'avr-size'),
    includePaths: [
      path.join(__dirname, 'arduino-headers'),
      path.join(__dirname, 'arduino-headers', 'avr'),
      path.join(__dirname, 'arduino-headers', 'variants', 'standard'),
      path.join(__dirname, 'arduino-libs'),
    ],
    cFlags: [
      '-mmcu=atmega328p',
      '-DF_CPU=16000000L',
      '-DARDUINO=10819',
      '-DARDUINO_AVR_UNO',
      '-DARDUINO_ARCH_AVR',
      '-Os',
      '-Wall',
      '-std=gnu11',
      '-fno-exceptions',
      '-ffunction-sections',
      '-fdata-sections',
      '-c',
    ],
    cppFlags: [
      '-mmcu=atmega328p',
      '-DF_CPU=16000000L',
      '-DARDUINO=10819',
      '-DARDUINO_AVR_UNO',
      '-DARDUINO_ARCH_AVR',
      '-Os',
      '-Wall',
      '-std=gnu++11',
      '-fno-exceptions',
      '-ffunction-sections',
      '-fdata-sections',
      '-fno-threadsafe-statics',
      '-c',
    ],
    linkerFlags: [
      '-mmcu=atmega328p',
      '-Wl,--gc-sections',
      '-Wl,-Map,',
      '-o',
    ],
    sizeFormat: 'avr',
    flashMax: 32768,
    ramMax: 2048,
  },

  arduino_nano: {
    name: 'Arduino Nano',
    toolchain: 'avr',
    mcu: 'atmega328p',
    fcpu: '16000000L',
    variant: 'standard',
    defines: [
      'ARDUINO=10819',
      'ARDUINO_AVR_NANO',
      'ARDUINO_ARCH_AVR',
      'F_CPU=16000000L',
    ],
    compiler: _toolchainPath('avr', 'bin', 'avr-gcc'),
    compilerCpp: _toolchainPath('avr', 'bin', 'avr-g++'),
    objcopy: _toolchainPath('avr', 'bin', 'avr-objcopy'),
    size: _toolchainPath('avr', 'bin', 'avr-size'),
    includePaths: [
      path.join(__dirname, 'arduino-headers'),
      path.join(__dirname, 'arduino-headers', 'avr'),
      path.join(__dirname, 'arduino-headers', 'variants', 'standard'),
      path.join(__dirname, 'arduino-libs'),
    ],
    cFlags: [
      '-mmcu=atmega328p',
      '-DF_CPU=16000000L',
      '-DARDUINO=10819',
      '-DARDUINO_AVR_NANO',
      '-DARDUINO_ARCH_AVR',
      '-Os',
      '-Wall',
      '-std=gnu11',
      '-fno-exceptions',
      '-ffunction-sections',
      '-fdata-sections',
      '-c',
    ],
    cppFlags: [
      '-mmcu=atmega328p',
      '-DF_CPU=16000000L',
      '-DARDUINO=10819',
      '-DARDUINO_AVR_NANO',
      '-DARDUINO_ARCH_AVR',
      '-Os',
      '-Wall',
      '-std=gnu++11',
      '-fno-exceptions',
      '-ffunction-sections',
      '-fdata-sections',
      '-fno-threadsafe-statics',
      '-c',
    ],
    linkerFlags: [
      '-mmcu=atmega328p',
      '-Wl,--gc-sections',
      '-Wl,-Map,',
      '-o',
    ],
    sizeFormat: 'avr',
    flashMax: 32768,
    ramMax: 2048,
  },

  esp32_devkit_v1: {
    name: 'ESP32 DevKit V1',
    toolchain: 'xtensa',
    mcu: 'esp32',
    fcpu: '240000000L',
    variant: 'devkit_v1',
    defines: [
      'ARDUINO=10819',
      'ARDUINO_ESP32_DEV',
      'ARDUINO_ARCH_ESP32',
      'CONFIG_IDF_TARGET="esp32"',
      'ESP_PLATFORM',
      'F_CPU=240000000L',
    ],
    compiler: _toolchainPath('xtensa', 'bin', 'xtensa-esp32-elf-gcc'),
    compilerCpp: _toolchainPath('xtensa', 'bin', 'xtensa-esp32-elf-g++'),
    objcopy: _toolchainPath('xtensa', 'bin', 'xtensa-esp32-elf-objcopy'),
    size: _toolchainPath('xtensa', 'bin', 'xtensa-esp32-elf-size'),
    includePaths: [
      path.join(__dirname, 'arduino-headers'),
      path.join(__dirname, 'arduino-headers', 'esp32'),
      path.join(__dirname, 'arduino-headers', 'variants', 'devkit_v1'),
      path.join(__dirname, 'arduino-libs'),
    ],
    cFlags: [
      '-mlongcalls',
      '-mtext-section-literals',
      '-mfix-esp32-psram-cache-issue',
      '-DF_CPU=240000000L',
      '-DARDUINO=10819',
      '-DARDUINO_ESP32_DEV',
      '-DARDUINO_ARCH_ESP32',
      '-DCONFIG_IDF_TARGET="esp32"',
      '-DESP_PLATFORM',
      '-Os',
      '-Wall',
      '-std=gnu11',
      '-fno-exceptions',
      '-ffunction-sections',
      '-fdata-sections',
      '-c',
    ],
    cppFlags: [
      '-mlongcalls',
      '-mtext-section-literals',
      '-mfix-esp32-psram-cache-issue',
      '-DF_CPU=240000000L',
      '-DARDUINO=10819',
      '-DARDUINO_ESP32_DEV',
      '-DARDUINO_ARCH_ESP32',
      '-DCONFIG_IDF_TARGET="esp32"',
      '-DESP_PLATFORM',
      '-Os',
      '-Wall',
      '-std=gnu++11',
      '-fno-exceptions',
      '-ffunction-sections',
      '-fdata-sections',
      '-fno-threadsafe-statics',
      '-c',
    ],
    linkerFlags: [
      '-mlongcalls',
      '-Wl,--gc-sections',
      '-Wl,-Map,',
      '-o',
    ],
    sizeFormat: 'xtensa',
    flashMax: 4194304,
    ramMax: 524288,
  },
};

module.exports = { BOARDS, TOOLCHAIN_DIR };
