var fs = require('fs');
var dest = process.argv[2];
var lines = [];

function w(s) { lines.push(s); }

w('/**');
w(' * Intel 8085 Two-Pass Assembler');
w(' * Supports all 8085 instructions, labels, directives, and number formats.');
w(' */');
w('window.Intel8085Assembler = (function () {');
w('    "use strict";');
w('');
w('    // ── Register encodings ──────────────────────────────────────────────────');
w('    var REG = { B: 0, C: 1, D: 2, E: 3, H: 5, L: 6, M: 7, A: 7 };');
w('');
w('    // Register pairs for LXI / DAD / INX / DCX / LDAX / STAX');
w('    var RP = { B: 0, D: 1, H: 2, SP: 3 };');
w('');
w('    // Register pairs for PUSH / POP');
w('    var RP_PSW = { B: 0, D: 1, H: 2, PSW: 3 };');
w('');
w('    // ALU base opcodes: ADD r ... CMP r  (opcode = base + reg)');
w('    var ALU = {');
w('        ADD: 0x80, ADC: 0x88, SUB: 0x90, SBB: 0x98,');
w('        ANA: 0xA0, XRA: 0xA8, ORA: 0xB0, CMP: 0xB8');
w('    };');
w('');
w('    // 8-bit immediate instructions (MVI r,d8 uses 0x06+reg*8)');
w('    var IMM8 = {');
w('        ADI: 0xC6, ACI: 0xCE, SUI: 0xD6, SBI: 0xDE,');
w('        ANI: 0xE6, XRI: 0xEE, ORI: 0xF6, CPI: 0xFE');
w('    };');
w('');
w('    // 16-bit memory instructions (opcode + addr16)');
w('    var MEM16 = {');
w('        LDA: 0x3A, STA: 0x32, LHLD: 0x2A, SHLD: 0x22');
w('    };');
w('');
w('    // Conditional jumps (2-byte: opcode + addr16)');
w('    var CJMP = {');
w('        JC: 0xDA, JNC: 0xD2, JZ: 0xCA, JNZ: 0xC2,');
w('        JP: 0xF2, JM: 0xFA, JPE: 0xEA, JPO: 0xE2');
w('    };');
w('');
w('    // Conditional calls (2-byte: opcode + addr16)');
w('    var CCALL = {');
w('        CC: 0xDC, CNC: 0xD4, CZ: 0xCC, CNZ: 0xC4,');
w('        CP: 0xF4, CM: 0xFC, CPE: 0xEC, CPO: 0xE4');
w('    };');
w('');
w('    // Conditional returns (1-byte)');
w('    var CRET = {');
w('        RC: 0xD8, RNC: 0xD0, RZ: 0xC8, RNZ: 0xC0,');
w('        RP: 0xF0, RM: 0xF8, RPE: 0xE8, RPO: 0xE0');
w('    };');
w('');
w('    // All known mnemonics for colon-less label detection');
w('    var _mnemonics = {};');
w('    (function () {');
w('        var names = [');
w('            "NOP","HLT","EI","DI","XCHG","SPHL","PCHL","XTHL",');
w('            "RLC","RRC","RAL","RAR","CMA","STC","CMC","DAA",');
w('            "MOV","MVI","LXI","LDAX","STAX","LDA","STA","LHLD","SHLD",');
w('            "ADD","ADC","SUB","SBB","ANA","XRA","ORA","CMP",');
w('            "ADI","ACI","SUI","SBI","ANI","XRI","ORI","CPI",');
w('            "INR","DCR","INX","DCX","DAD",');
w('            "JMP","CALL","RET","RST",');
w('            "JC","JNC","JZ","JNZ","JP","JM","JPE","JPO",');
w('            "CC","CNC","CZ","CNZ","CP","CM","CPE","CPO",');
w('            "RC","RNC","RZ","RNZ","RP","RM","RPE","RPO",');
w('            "PUSH","POP","IN","OUT",');
w('            "ORG","EQU","END","DB","DW",');
w('            "B","C","D","E","H","L","M","A","SP","PSW"');
w('        ];');
w('        for (var i = 0; i < names.length; i++) _mnemonics[names[i]] = true;');
w('    })();');
w('');
w('    function isMnemonic(token) {');
w('        return _mnemonics[token.toUpperCase()] === true;');
w('    }');
w('');
w('    // ── Number parsing helper ────────────────────────────────────────────────');
w('    function parseNumber(s) {');
w('        if (s == null || s === "") return null;');
w('        s = s.trim();');
w('        if (/^0[bB][01]+$/.test(s))                     return parseInt(s.substring(2), 2);');
w('        if (/^[0-9a-fA-F][0-9a-fA-F]*[hH]$/.test(s))    return parseInt(s.substring(0, s.length - 1), 16);');
w('        if (/^0[xX][0-9a-fA-F]+$/.test(s))              return parseInt(s, 16);');
w('        if (/^[0-9]+$/.test(s))                          return parseInt(s, 10);');
w('        if (/^-[0-9]+$/.test(s))                         return parseInt(s, 10);');
w('        return null;');
w('    }');
w('');
w('    // ── Strip comments ──────────────────────────────────────────────────────');
w('    function cleanSource(source) {');
w('        var lines = source.split(/\\r?\\n/);');
w('        var result = [];');
w('        for (var i = 0; i < lines.length; i++) {');
w('            var line = lines[i];');
w('            var ci = line.indexOf(";");');
w('            if (ci >= 0) line = line.substring(0, ci);');
w('            ci = line.indexOf("//");');
w('            if (ci >= 0) line = line.substring(0, ci);');
w('            result.push(line);');
w('        }');
w('        return result;');
w('    }');
w('');
w('    // ── Tokenize a single line ──────────────────────────────────────────────');
w('    function tokenize(line) {');
w('        return line.split(/[,\\s]+/).filter(function (t) { return t.length > 0; });');
w('    }');
w('');
w('    // ── Expression evaluator ────────────────────────────────────────────────');
w('    function evalExpr(tokenStr, labels, pc) {');
w('        var s = tokenStr.trim();');
w('        s = s.replace(/\\$/g, "(" + pc + ")");');
w('        var labelNames = Object.keys(labels);');
w('        labelNames.sort(function (a, b) { return b.length - a.length; });');
w('        for (var i = 0; i < labelNames.length; i++) {');
w('            var re = new RegExp("\\\\b" + labelNames[i].replace(/[-\\/\\\\^$*+?.()|[\\]{}]/g, "\\\\$&") + "\\\\b", "g");');
w('            s = s.replace(re, "(" + labels[labelNames[i]] + ")");');
w('        }');
w('        // Hex suffix -> 0x prefix');
w('        s = s.replace(/\\b([0-9a-fA-F][0-9a-fA-F]*)[hH]\\b/g, function (m, num) {');
w('            return "0x" + num;');
w('        });');
w('        // Binary literal');
w('        s = s.replace(/\\b0[bB]([01]+)\\b/g, function (m, num) {');
w('            return "0b" + num;');
w('        });');
w('        // Strip leading zeros from plain decimals to avoid octal in strict mode');
w('        s = s.replace(/\\b0+(\\d+)\\b/g, function (m, digits) {');
w('            return digits;');
w('        });');
w('        try {');
w('            if (/^[0-9a-fA-FxXbB\\s+\\-*/()]+$/.test(s)) {');
w('                var val = Function("\\"use strict\\"; return (" + s + ")")();');
w('                if (typeof val === "number" && isFinite(val)) return val | 0;');
w('            }');
w('        } catch (e) { /* fall through */ }');
w('        return NaN;');
w('    }');
fs.writeFileSync(dest, lines.join('\n'), 'utf8');
console.log('Part 1 written: ' + lines.length + ' lines');
