var fs = require('fs');
var dest = process.argv[2];
var lines = [];

function w(s) { lines.push(s); }

// Read existing content
var existing = fs.readFileSync(dest, 'utf8');

w('');
w('    // ── Compute size of one instruction (pass 1 helper) ────────────────────');
w('    function instrSize(tokens, pc, labels) {');
w('        var op = tokens[0].toUpperCase();');
w('        if (op === "ORG") return 0;');
w('        if (op === "EQU") return 0;');
w('        if (op === "END") return 0;');
w('        if (op === "DB") {');
w('            var total = 0;');
w('            for (var i = 1; i < tokens.length; i++) {');
w('                var t = tokens[i];');
w('                if (t.charAt(0) === \'"\') { total += t.length - 2; } else { total += 1; }');
w('            }');
w('            return total;');
w('        }');
w('        if (op === "DW") return (tokens.length - 1) * 2;');
w('        if (op === "NOP") return 1;');
w('        if (op === "MOV") return 1;');
w('        if (op === "MVI") return 2;');
w('        if (op === "LXI") return 3;');
w('        if (op === "LDAX" || op === "STAX") return 1;');
w('        if (MEM16[op]) return 3;');
w('        if (op === "XCHG" || op === "SPHL" || op === "PCHL" || op === "XTHL") return 1;');
w('        if (ALU[op]) return 1;');
w('        if (IMM8[op]) return 2;');
w('        if (op === "INR" || op === "DCR") return 1;');
w('        if (op === "INX" || op === "DCX" || op === "DAD") return 1;');
w('        if (op === "DAA" || op === "CMA" || op === "STC" || op === "CMC") return 1;');
w('        if (op === "RLC" || op === "RRC" || op === "RAL" || op === "RAR") return 1;');
w('        if (op === "JMP" || CJMP[op]) return 3;');
w('        if (op === "CALL" || CCALL[op]) return 3;');
w('        if (op === "RET" || CRET[op]) return 1;');
w('        if (op === "RST") return 1;');
w('        if (op === "PUSH" || op === "POP") return 1;');
w('        if (op === "EI" || op === "DI" || op === "HLT") return 1;');
w('        if (op === "IN" || op === "OUT") return 2;');
w('        return 0;');
w('    }');
w('');
w('    // ── Parse line: extract optional label + opcode + remaining tokens ──────');
w('    function parseLine(tokens) {');
w('        var label = null;');
w('        if (tokens.length === 0) return { label: null, op: null, tokens: [] };');
w('        var first = tokens[0];');
w('');
w('        // Colon label: LABEL: ...');
w('        if (first.charAt(first.length - 1) === ":") {');
w('            label = first.substring(0, first.length - 1).toUpperCase();');
w('            tokens = tokens.slice(1);');
w('        } else if (tokens.length > 1 && !isMnemonic(first) && isMnemonic(tokens[1])) {');
w('            // Colon-less label before directive (e.g. COUNT EQU 10)');
w('            label = first.toUpperCase();');
w('            tokens = tokens.slice(1);');
w('        }');
w('');
w('        if (tokens.length === 0) return { label: label, op: null, tokens: [] };');
w('        return { label: label, op: tokens[0].toUpperCase(), tokens: tokens };');
w('    }');
w('');
w('    // ══════════════════════════════════════════════════════════════════════════');
w('    //  PASS 1 - collect labels and compute addresses');
w('    // ══════════════════════════════════════════════════════════════════════════');
w('    function pass1(lines) {');
w('        var labels = {};');
w('        var errors = [];');
w('        var pc = 0;');
w('        var foundEnd = false;');
w('');
w('        for (var li = 0; li < lines.length; li++) {');
w('            var raw = lines[li].trim();');
w('            if (raw === "") continue;');
w('            var tokens = tokenize(raw);');
w('            if (tokens.length === 0) continue;');
w('');
w('            var parsed = parseLine(tokens);');
w('            var label = parsed.label;');
w('            var op = parsed.op;');
w('            tokens = parsed.tokens;');
w('');
w('            // Register label');
w('            if (label) {');
w('                if (labels.hasOwnProperty(label)) {');
w('                    errors.push({ line: li + 1, message: "Duplicate label \'" + label + "\'" });');
w('                } else {');
w('                    labels[label] = pc;');
w('                }');
w('            }');
w('');
w('            if (!op) continue;');
w('');
w('            if (op === "ORG") {');
w('                var addr = evalExpr(tokens[1], labels, pc);');
w('                if (isNaN(addr)) {');
w('                    errors.push({ line: li + 1, message: "Invalid ORG expression" });');
w('                } else {');
w('                    pc = addr & 0xFFFF;');
w('                }');
w('                continue;');
w('            }');
w('            if (op === "EQU") {');
w('                if (!label) {');
w('                    errors.push({ line: li + 1, message: "EQU without label" });');
w('                } else {');
w('                    var val = evalExpr(tokens[1], labels, pc);');
w('                    if (isNaN(val)) {');
w('                        errors.push({ line: li + 1, message: "Invalid EQU expression" });');
w('                    } else {');
w('                        labels[label] = val & 0xFFFF;');
w('                    }');
w('                }');
w('                continue;');
w('            }');
w('            if (op === "END") { foundEnd = true; break; }');
w('');
w('            var size = instrSize(tokens, pc, labels);');
w('            if (size === 0) {');
w('                errors.push({ line: li + 1, message: "Unknown instruction \'" + op + "\'" });');
w('            }');
w('            pc += size;');
w('        }');
w('        return { labels: labels, errors: errors, foundEnd: foundEnd };');
w('    }');

fs.writeFileSync(dest, existing + lines.join('\n'), 'utf8');
console.log('Part 2 written: ' + lines.length + ' lines');
